### ISSUE TITLE
Segmentation fault before replying

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-client-cpp#1]
Fresh build today, armv7, running on baremetal.

Backtrace:
```
(gdb) bt full
#0  0xb6b6b976 in gst_element_set_state (element=0x1, state=GST_STATE_PLAYING) at ../subprojects/gstreamer/gst/gstelement.c:2896
        __inst = 0x1
        __t = 2159443888
        __r = <optimized out>
        oclass = <optimized out>
#1  0x7f5e7544 in genie::AudioPlayer::resume (this=0x80b60a00) at ../src/audioplayer.cpp:407
No locals.
#2  0x7f5e784e in genie::STT::on_message (conn=0x80b732a8, type=1, message=0x813f6c20, data=0x80b8cc50) at ../src/stt.cpp:94
        obj = 0x80b8cc50
        status = 400
        sz = 34
        ptr = 0x811e5fb8 "{\"status\":400,\"code\":\"E_NO_MATCH\"}"
        parser = 0x81267170
        reader = 0x80cbb890
        __func__ = "on_message"
```

Logs:
```
Conversation id: main
Start speak text: Hello! How can I help you?
[02:22:19.37448] on_message (../src/wsclient.cpp:153): Start speak text: Hello! How can I help you?
[02:22:19.61684] dispatch_queue (../src/audioplayer.cpp:357): gst pipeline started
[02:22:19.178266] bus_call_queue (../src/audioplayer.cpp:89): Stream status changed
[02:22:19.178685] bus_call_queue (../src/audioplayer.cpp:89): Stream status changed
[02:22:20.793676] bus_call_queue (../src/audioplayer.cpp:89): Stream status changed
[02:22:24.197840] bus_call_queue (../src/audioplayer.cpp:93): End of stream
[02:22:24.197929] bus_call_queue (../src/audioplayer.cpp:94): Pipeline elapsed: 5136153us
[02:22:24.956941] loop (../src/audioinput.cpp:234): detected keyword
detected keyword
Gst element could not be created
[02:22:27.936971] dispatch_queue (../src/stt.cpp:209): STT xfer elapsed: 1025007us
[02:22:27.937101] loop (../src/audioinput.cpp:256): STT last frame
STT status 400
Gst element could not be created
Resume current pipeline
Segmentation fault (core dumped)
```

[corefile-genie-1035-1629138148.gz](https://github.com/stanford-oval/genie-client-cpp/files/6994579/corefile-genie-1035-1629138148.gz)

**Comment by ad31c0** [comment]
This should've been addressed with the latest master
